### PR TITLE
Chore: Functional Tests (Magellan, Rowdy, Sauce)

### PR DESCRIPTION
**Pull request by ryan-roemer**
OK, I think this is ready for review.

### Outstanding Issues

Sauce Labs `safari_7_OS_X_10_9_Desktop` keeps failing. We have https://github.com/walmartlabs/little-loader/issues/5 to track and hopefully will solve _in_ this PR.

### Notes

* Adds magellan + rowdy + webdriverio
* @Maciek416 -- This is probably a good starting point for a refactoring / tightening of the magellan + rowdy boilerplate
* Tests a very basic and slightly more advanced scenario
* Hooks up Sauce to Travis and implements WML's browser support matrix of tests
* Also tests ff + phantom locally on Travis

/cc @Maciek416 @geekdave @exogen

### CODE REVIEW

**Comment by Maciek416** [comment]
Looking good. Is all sauce-related config via travis?

**Comment by Maciek416** [comment]
What set of sauce browsers is this going to be tested against?

**Comment by exogen** [comment]
LGTM. Adding more real tests will necessitate spinning up more than one `http-server` (unless you're OK with tests hitting real CDN servers). Loading scripts from the same origin as the test page would allow the loader to "cheat" since it could just read the script's contents and execute it however it likes, without worrying about the same-origin policy. (I'm just mentioning this you so you can decide how you want to manage spinning up those extra servers now, instead of letting whoever adds the tests decide. Or we could avoid that and hit a CDN; I just assumed you didn't wanna hit the network.)

**Comment by ryan-roemer** [comment]
@exogen -- Thanks for the review! For:

> Adding more real tests will necessitate spinning up more than one http-server 

Since magellan parallelizes things, we actually already spin up multiple `http-server` instances, just use `FUNC_PORT` given from Magellan to make sure we don't conflict locally... (At least I _think_ that's how it works)

/cc @Maciek416 @geekdave

**Comment by ryan-roemer** [comment]
@exogen -- And "different" domain / CDN sounds great for a test scenario. Captured in #6

**Comment by exogen** [comment]
@ryan-roemer Ah I think we're talking about different things. I'm talking about the test page loading: `advanced/first.js` which is the same origin as the test page. We're gonna need tests like `//localhost:SOME_OTHER_PORT/advanced/first.js`. In the `advanced/first.js` case, the loader can just read that script's contents willy-nilly since it's same-origin.

**Comment by exogen** [comment]
Yup, that PR captures it – only reason I suggested CDNs though is because it's an easy way to test other origins without spinning up more local servers. But if we spun up more local servers, we wouldn't have to hit the network...

**Pull request merged**
