### PR TITLE
Switch to using JWT auth for sauce labs

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by halkeye** [comment]
Re: #43 #46 
Trying a new patch

Really not sure if its your repo isn't in travis anymore, or something more serious has broken
@ryan-roemer @BanzaiMan

**Comment by BanzaiMan** [comment]
Someone has disabled Travis CI on this repository.

**Comment by BanzaiMan** [comment]
So no builds are running and all the PR commits have been lost.

**Comment by ryan-roemer** [comment]
@BanzaiMan @halkeye -- I didn't touch anything, but going to Travis it had a "this is not an active repo" message. I clicked the "activate" button and now I'm going to close and reopen this PR to see if Travis picks up.

**Comment by ryan-roemer** [comment]
@halkeye -- Alrighty, we're all green and that picked up quickly in Travis, so I'm consider us **done**.

@BanzaiMan -- Is there something like an audit log on this project's Travis page that can tell me what happened to disable travis? I _might_ have fat fingered something, but I don't think so.

And thanks again all around. This is a huge convenience for the many projects that are fortunate enough to get forked PRs!

**Comment by halkeye** [comment]
I bet it got auto disabled when the jobs were stuck for a long time not running

**Pull request merged**
