### PR TITLE
Add `{callback, setup, context}` options as alternative to `callback`.

### PR DESCRIPTION
**Pull request by ryan-roemer**
Extra commits on top of @jknight12882 's excellent https://github.com/walmartlabs/little-loader/pull/49

@jknight12882 -- I can either keep going with this and squash the whole thing down (which would lose your git commit attributions, but we've got your name in HISTORY), or you can rebase your PR with these changes and we'll keep going on #49 

@exogen -- How do all these changes look together? Any pitfalls we're missing?

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@exogen -- Also note that **all** of our Travis builds were disabled for all `walmartlabs` repos weirdly. I've started reenabling the ones we currently use. You may want to peek at other repos under `walmartlabs`...

**Comment by jknight12882** [comment]
No need to keep my git history. Squash away!

**Comment by ryan-roemer** [comment]
@jknight12882 -- Great! (We're just waiting on @exogen to finish up his PTO and approve this, then I'll publish)

**Comment by ryan-roemer** [comment]
Released in `little-loader@0.2.0`

**Pull request merged**
