### PR TITLE
Shrink it a bit

### PR DESCRIPTION
**Pull request by pygy**
I'm submitting this perhaps prematurely because of #30, hoping that Travis will save the day...

Got the mingzipped size down to 474 bytes (-28), at the expense of the minified size: 876 (+11).

The second diff is a bit dirty because I moved the `_finish` definition before `_error`, since the latter references the former.

### CODE REVIEW

**Comment by pygy** [comment]
Aaarrg, now I get what you meant by "there may be some issues with PR verifying of forks for sauce credentials".

If you want, this will push my branch to your repo, for Sauce to kick in (I suppose you know it, but now you can just copy/paste it ;-)).

```Shell
cd tmp
git clone https://github.com/pygy/little-loader.git
cd little-loader
git remote add wml https://github.com/walmartlabs/little-loader.git
git checkout shrink #? may not even be needed
git push wml shrink
```

**Comment by ryan-roemer** [comment]
@pygy -- Thanks for the PR! I'm going to copy your diff into a branch and open a new PR off that as Sauce Labs + Travis has an awkward bug of "can't use existing credentials". (And you'll get the credit in our changelog :wink: )

**Comment by pygy** [comment]
Great, thanks :-)

**Comment by ryan-roemer** [comment]
@pygy -- I'm going to open up a parallel PR to this one. You can update this one if you want to put in more optimizations. That said, let's make sure to get your local `npm run check` working...

**Comment by pygy** [comment]
Any reason why you're appending before the last script rather than at the end of `head`? The sizes go down to 467 / 856.

**Comment by ryan-roemer** [comment]
> Any reason why you're appending before the last script rather than at the end of head? The sizes go down to 467 / 856.

@exogen , the creator of this madness I'm sure knows the answer to your question. (I'm just the one who wrapped a ton of tests around Brian's script and added the error capture)

**Comment by exogen** [comment]
`head` doesn't necessarily always exist, you'll see errors if you blindly try to append to `head`.

We know there's at least a `<script>` element on the page because little-loader itself must have been loaded somehow – UNLESS of course some terribly misbehaving script removed it (in that case I'd support appending to `document.body` as a backup, but I've never seen the current method fail).

**Comment by exogen** [comment]
^ to follow up, here's an example of a script loader in the `script-atomic-onload` build matrix that gets this wrong: https://travis-ci.org/exogen/script-atomic-onload/jobs/98008707#L362

In IE8, `getscript` fails with `'document.head' is null or not an object`. It's possibly that it might work if it used `document.getElementByTagName('head')` instead, but then again having an actual `<head>` element is not a guarantee.

**Comment by pygy** [comment]
LGTM, then :-)

**Comment by pygy** [comment]
Still I'm curious, beside deliberate sabotage, when could the `head` be absent?

```JS
<!doctype html>
<script>
console.log(document.getElementsByTagName("head")[0]) // <head></head>
console.log(document.getElementsByTagName("body")[0]) // undefined
</script>
```

This works in FF, Chrome and Safari, and IIRC that's also the case in (old) IE (I have little hands on experience with recent IE).

**Comment by ryan-roemer** [comment]
Merged in with #32 instead.

**Pull request closed without merging**
